version: '3.8'

services:
    uniomotors:
        image: kooldev/php:8.1
        container_name: uniomotors
        working_dir: /uniomotors
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - '.:/uniomotors'
            - './docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        links:
            - uniomotors-database
        depends_on:
            - uniomotors-database
        environment:
            - PHP_EXECUTABLE_PATH=/usr/local/bin/php
    uniomotors-nginx:
        image: nginx:alpine
        container_name: uniomotors-nginx
        restart: always
        working_dir: /uniomotors
        networks:
            - internal
            - nginx_network
        ports:
            - "9002:80"
        volumes:
            - .:/uniomotors
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - uniomotors
    uniomotors-composer:
        image: composer:latest
        container_name: uniomotors-composer
        working_dir: /uniomotors
        command: update --ignore-platform-reqs
        volumes:
            - .:/uniomotors
        restart: on-failure
        depends_on:
            - uniomotors
    uniomotors-database:
        image: mariadb:latest
        restart: always
        container_name: uniomotors-database
        working_dir: /uniomotors
        networks:
            - internal
            - nginx_network
        command: mysqld --skip-grant-tables
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=uniomotors
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        volumes:
            - .:/uniomotors
            - ./uniomotors-database:/var/lib/mysql
        ports:
            - '8000:3306'
    uniomotors-redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - uniomotors-redis:/data
        networks:
            - internal
            - nginx_network
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    uniomotors-npm:
        image: node:20-alpine
        container_name: uniomotors-npm
        working_dir: /uniomotors
        volumes:
            - '.:/uniomotors'
        depends_on:
            - uniomotors

networks:
    nginx_network:
        external: true
    internal:
        driver: overlay
        name: 'global'
        attachable: true
volumes:
    uniomotors-database:
        driver: local
    uniomotors-redis:
        driver: local
